# Generated by Django 5.0.2 on 2024-02-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_postulante_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_edu', models.CharField(max_length=255)),
                ('pais_edu', models.CharField(max_length=255)),
                ('institucion_edu', models.CharField(max_length=255)),
                ('nivel_edu', models.CharField(max_length=255)),
                ('estado_edu', models.CharField(max_length=255)),
                ('descripcion_edu', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_exp', models.CharField(max_length=255)),
                ('empresa_exp', models.CharField(max_length=255)),
                ('pais_exp', models.CharField(max_length=255)),
                ('area_exo', models.CharField(max_length=255)),
                ('finicio_exp', models.DateField()),
                ('ffinal_exp', models.DateField(blank=True, null=True)),
                ('descripcion_exp', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
