# Generated by Django 5.0.2 on 2024-02-21 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_educacion_experiencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educacion',
            options={'verbose_name_plural': 'Educacion'},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'verbose_name_plural': 'Experiencia'},
        ),
        migrations.AddField(
            model_name='educacion',
            name='id_educacion_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulanteedu', to='app.postulante'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='id_experiencia_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulanteexp', to='app.postulante'),
        ),
        migrations.AlterField(
            model_name='detallepostulante',
            name='id_postulante_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulante', to='app.postulante'),
        ),
    ]
