# Generated by Django 5.0.2 on 2024-02-21 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_educacion_options_alter_experiencia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveltitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=144)),
            ],
            options={
                'verbose_name_plural': 'Niveltitulo',
            },
        ),
        migrations.AlterField(
            model_name='educacion',
            name='titulo_edu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nivelid', to='app.niveltitulo'),
        ),
    ]
