# Generated by Django 5.0.2 on 2024-02-21 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_niveltitulo_alter_educacion_titulo_edu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacion',
            name='nivel_edu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nivelid', to='app.niveltitulo'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='titulo_edu',
            field=models.CharField(max_length=255),
        ),
    ]
